### PR TITLE
[Breaking change] ARIA 1.2 Combobox

### PR DESCRIPTION
**Pull request by muan**
Ref: https://github.com/github/auto-complete-element/pull/41

https://github.com/w3c/aria/wiki/Resolving-ARIA-1.1-Combobox-Issues

> One way to fix all these problems is to eliminate the container and make the combobox more like a menubutton. This is essentially returning to the 1.0 pattern with one small modification -- use aria-controls to specify the input-popup relationship instead of aria-owns.

This changes `aria-owns` to `aria-controls`.

---

cc @jscholes This is the underlying module that powers auto-complete, which implements just the keyboard navigation with `aria-activedescendant`, not the filtering nor the expanding/collapsing. [Test page](https://html-is.glitch.me/github/combobox-nav-20.html#wall-e). Once this goes through I'll update https://github.com/github/auto-complete-element/pull/41 to remove `aria-owns`.

### CODE REVIEW

**Comment by jscholes** [comment]
@muan 

> This is the underlying module that powers auto-complete, which implements just the keyboard navigation with aria-activedescendant, not the filtering nor the expanding/collapsing.

Understood re: the filtering, because that is specific to each use case.  But the expanded/collapsed state is integral to a combo box control and it's difficult to test without it.  It will also heavily impact the UX if it isn't handled correctly.

For example, when I load the test case in both Firefox and Chrome, the combo box seems to be expanded by default.  This is non-standard, and NVDA immediately jumps into the list box for some reason.  What's the context behind the auto-complete module not handling expanded/collapsed state?

**Comment by muan** [comment]
> What's the context behind the auto-complete module not handling expanded/collapsed state?

The `<auto-complete>` element does handles expanded/collapsed state. The example page here is for combobox-nav alone, and it does not use auto-complete. The demo page shows it as expanded by default for testing how activedescendant changes. If it'd help I can add a basic expand/collapse handling logic to the demo page.

**Comment by muan** [comment]
> It will also heavily impact the UX if it isn't handled correctly.

To be clear, it is expected for the user of `combobox-nav` module to handle those states. In this PR I included this note in the README:

> The combobox navigation pattern does not control list visibility. Please [refer to the ARIA spec](https://www.w3.org/TR/wai-aria-1.2/#combobox) for more requirements around `aria-expanded` and `aria-autocomplete`.

**Comment by muan** [comment]
@github/web-systems In 9b87f70 changed it so that now `combobox-nav` sets ARIA attributes instead of the developers. This way we 

1. prevent human error in markup 
2. avoid future spec change requiring more breaking changes 
3. ensure that the role only exist on the elements when ARIA behaviors are attached

**Comment by jscholes** [comment]
> If it'd help I can add a basic expand/collapse handling logic to the demo page.

That would definitely help.  And in terms of getting this pattern deployed across GitHub, we can focus on those use cases and getting them right.  I don't want anything to block on this PR specifically, if the mark-up is technically correct.  However...

> The combobox navigation pattern does not control list visibility. Please refer to the ARIA spec for more requirements around aria-expanded and aria-autocomplete.

This isn't a recipe for success, particularly in this case.  `aria-expanded` is a core, required part of the combo box pattern.  Without it, or with incorrect application, you don't have a combo box.  If developers decide to ignore this advice, or miss it entirely, they will create mark-up which acts strangely at best, and is not accessible at worst.

There will be differing opinions re: the delineation of responsibility for something like this, whether that be related to actions taken by other devs or just the scope of the component as a whole.  But my priority is always to help developers do the right thing.  For assistive technology and keyboard users, combo box navigation can't really be separated from other aspects of combo box behaviour like its expanded state.  Particularly given that `aria-expanded` needs to go on the element with `role="combobox"`, and leaving it out creates an invalid control.

**Comment by muan** [comment]
@jscholes I feel like there’s something lost here. I don’t disagree that it’s important, but as you’ve said

> Understood re: the filtering, because that is specific to each use case. 

It is exactly because combobox-nav does not know about the filtering operations, that it can not decide the aria-expanded state. It can’t set aria-expanded to true as it doesn’t know when filtering finished, or if the filtering logic decided nothing should be shown. 

combobox-nav isn’t a component by itself, but a set of functions to install/uninstall keyboard event handlers as expected for a combobox pattern. For example, auto-complete element installs the combobox-nav behavior, then fetches from a remote source as you type. auto-complete sanitizes the input value for filtering, sending it to the server to get filtered results, and install activation behaviors on the result elements. It knows when to flip aria-expanded state and to what, combobox-nav doesn’t.

We extracted combobox-nav because we have multiple components needing to include the code here for handling arrow keys and setting active descendant but has different ways of retrieving options. The alternative is to copy all the code here and include them separately in each of the component we build that has different filtering logic.

**Comment by jscholes** [comment]
@muan I understand that this is more of a pattern than a full component.  And I absolutely agree that on its own, the code presented here cannot know everything it needs to know to set `aria-expanded`.  But that isn't the issue I'm highlighting.  The primary thing I'm raising for discussion is the requirement for implementers of this pattern to understand ARIA concepts, which is problematic for several reasons:

1. It increases cognitive load.  Developers understand that a combo box can be open or closed, but now they have to map that understanding to an ARIA attribute and an appropriate value.
2.  It drastically increases the potential for technical debt.  Across WAI-ARIA 1.0, 1.1 and 1.2, the combo box pattern has changed three times.  In 1.3, it will change again.  In 5 years time, we might not even be using ARIA directly for something like this, because we've decided that Web Components or something are the way forward.  But we'll probably be still using combo boxes.  Each time a minor or major change occurs, implementers have to be made aware of it and apply it in every single place this pattern is deployed.
3.  It increases the chances of an unusable component.  This is inescapable.  If somebody gets the styling wrong for a combo box, the worst outcome is that it looks a bit wonky.  Maybe it even makes some other things on the page look a bit weird.  But if they get the application of ARIA wrong, the component can become unusable for those with disabilities or other additional needs.  It is my priority to attempt to avoid that.  Even if this discussion doesn't map to an immediate change, it is worth discussing and thinking about how we can increase the chances of components being built accessibly the first time, every time.

This comes back to several discussions we've had recently.  The need for accessibility awareness during experimentation, the fact that JS is required to resolve incorrect applications of `role="menu"`, etc.  And that's before we even move on to talking about `aria-autocomplete`...

So in essence, I'm not advocating for an all-seeing, all-knowing combo box component.  But I am suggesting that wherever possible, technical implementation details like individual ARIA attributes should be abstracted away behind actionable, understandable things which developers will 100% just use without question (like a function/method call, event fire to say that the combo box has opened or closed, data attributes to identify the corresponding list for the input, etc.).

I don't even think implementers should be responsible for setting `role="combobox"`, `aria-controls`, `role="listbox"` or `role="option"` because these do change (and have changed which is why this PR exists).  Let the developer create an input and a container for their options, and then somehow inform the JS behind the pattern about which is which.  Then, in ARIA 1.3, they don't need to change anything (or even know about the changes) because you can just update the JavaScript code path responsible for setting the attributes and attaching behaviours.

Happy to talk about this further, but I really do think that reusable components have huge potential to increase accessibility across the board.  But not unless they come with clear, actionable instructions and/or abstracted functionality to avoid ARIA being done wrong.

Either way, I do want to highlight this sentence from the WAI-ARIA 1.2 Authoring Practices document, within the combo box design pattern:

> The popup is hidden by default, i.e., the default state is collapsed.

Regardless of how you decide to move forward with this pattern, `aria-expanded` must be present by default, and set to "false".

**Comment by muan** [comment]
@jscholes What I was trying to distinguish is that the users of `combobox-nav` is us, as in people on our team, who use combobox to build fully fledged components. Product engineers then use those fully-fledged components, they don't use combobox. The expectation to understand ARIA combobox on us, the component builders, which seems reasonable.

**Comment by jscholes** [comment]
> The expectation to understand aria-expanded and aria-autocomplete on us, the component builders, which seems reasonable.

That makes sense, but I don't want us to lose sight of the fact that this PR was, at least in part, triggered by us being unable to test an inaccessible component.  This may be a discussion we should have elsewhere, because I understand why you believe that it doesn't strictly apply to this pattern directly.  But it does apply in other places, so is worth raising.  And regardless of the intended audience, I never think it's a bad idea to abstract appropriate details away for the purposes of increasing consistency.

**Comment by jscholes** [comment]
CC @sinabahram

**Comment by muan** [comment]
@jscholes Apologies. I talked this through with the team and look through the call sites, looks like components are all setting `aria-expanded` at the time of `comboboxNav.install`, which makes sense as that's when keyboard handling gets taken over aka when the listbox shows up.

**Comment by muan** [comment]
@jscholes Thanks for the discussions. I decided to make bigger API changes to this module so I'm closing this and starting a new thread.

**Pull request closed without merging**
