### PR TITLE
Use `Element.scrollIntoView`

### PR DESCRIPTION
**Pull request by seanpdoyle**
Related to [@github/auto-complete-element#91][]

The current `scrollTo` helper method implementation can be unreliable (or have no effect) at times.

This commit replaces it with a call to [Element.scrollIntoView][]. To control that behavior, this commit also introduces a `scrollIntoViewOptions:` key to the package's constructor call.

[@github/auto-complete-element#91]: https://github.com/github/auto-complete-element/issues/91
[Element.scrollIntoView]: https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView
[ScrollIntoViewOptions]: https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView#sect1

### CODE REVIEW

**Comment by seanpdoyle** [comment]
@keithamus I did a preliminary search for attempts to replace the `scrollTo` implementation with calls to `Element.scrollIntoView`, but came up empty:

```
~/Work/github/combobox-nav main
❯ git log -SscrollIntoView

```

A quick dive into `git blame` yielded [a commit that copied the `scrollTo` implementation from `github/auto-complete-element`](https://github.com/github/combobox-nav/commit/5c0b27bfece71b4365fd901137b96fcf8d930ec9). A [search for `scrollIntoView` on that project](https://github.com/search?q=repo%3Agithub%2Fauto-complete-element%20scrollIntoView&type=code) didn't yield any results.

Has this been attempted in the past?

**Comment by primer-css** [comment]
:wave: Hello and thanks for pinging us! This issue or PR has been added to our inbox and a Primer first responder will review it soon.
- :art: **If this is a PR that includes a visual change**, please make sure to add screenshots in the description or deploy this code to a lab machine with instructions for how to test.
- :fast_forward: **If this is a PR that includes changes to an interaction**, please include a [video recording](https://support.apple.com/en-us/HT208721) in the description.
- :warning: **If this is urgent**, please visit us in [#primer](https://github.slack.com/archives/CSGAVNZ19) on Slack and tag the first responders listed in the channel topic.

**Comment by broccolinisoup** [comment]
@keithamus is this something you can take on to answer or do you prefer for me to look as a FR?

**Comment by keithamus** [comment]
I’ll take a look thanks @broccolinisoup

**Review by camertron — APPROVED** [review]

**Comment by nicowenterodt** [comment]
The use of [Element.scrollIntoView](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView) is really helpful. I checked this and it works wonderful especially if you need to control the scroll position and behavior of it as easy as defining an option like this `element.scrollIntoView({ behavior: "smooth", block: "end", inline: "nearest" });` 

Thanks @seanpdoyle 👏 

I would love to see this one merged @keithamus.

**Comment by keithamus** [comment]
I agree I just want to check some internal codebases to double check if there are any blockers before we merge. I'm a little short on time this week so I'll most likely get to this next week.

**Review by keithamus — APPROVED** [review]

**Comment by keithamus** [comment]
macos build failing for some reason. I'll figure that out separately.

**Pull request merged**
