### PR TITLE
Support for `[role="textbox"][contenteditable]` input

### PR DESCRIPTION
**Pull request by seanpdoyle**
This changeset contains a large chunk or indentation changes, and is best reviewed [ignoring spacing changes](https://github.com/github/combobox-nav/pull/62/files?w=1)

---

Related to https://github.com/github/combobox-nav/pull/52

As a follow up, relax the `Combobox.input` property's type expectations
from `HTMLInputElement | HTMLTextAreaElement` to `HTMLElement`, with the
caveat that the `HTMLElement` must have the `[contenteditable]`
attribute.

### CODE REVIEW

**Comment by jscholes** [comment]
@seanpdoyle Can you please explain the use case that requires this change?  `contenteditable` is an extremely high-risk attribute/pattern for accessibility purposes, and its use requires strong justification.

In addition, if `contenteditable` is permitted by the component, there should be more restrictions to avoid text inputs that are incompatible with the combobox model.  As a minimum, `role="textbox"` and `aria-multiline="false"` are also required, along with appropriate code paths to ensure that the `contenteditable` area is actually single-line only.

**Comment by seanpdoyle** [comment]
> Can you please explain the use case that requires this change?

Sure! The main motivating use case behind this proposal is a desire to wrap [`<text-expander>`](https://github.com/github/text-expander-element) around a [`<trix-editor>`](https://github.com/basecamp/trix#creating-an-editor) (a What You See is What You Get text editor custom element that relies on `[contenteditable]`).

Currently, the `TextExpander` implementation has an [explicit guard to ignore any elements that are not `HTMLInputElement` or `HTMLTextAreaElement` instances](https://github.com/github/text-expander-element/blob/89b3580f2e875b004d0609f9411eb39966dda412/src/text-expander-element.ts#L243). On top of that, the `Combobox` instance that's at-work under the hood also [rejects elements that are not `HTMLInputElement` or `HTMLTextAreaElement` instances](https://github.com/github/text-expander-element/blob/89b3580f2e875b004d0609f9411eb39966dda412/src/text-expander-element.ts#L83).

I'm hoping for this changeset I dovetail with a separate PR to add support to `<text-expander>` elements for wrapping `[contenteditable]` elements.

> along with appropriate code paths to ensure that the contenteditable area is actually single-line only

How does `<text-expander>` account for the fact that `<textarea>` elements are multi-line? Does `Combobox` guard against `HTMLTextAreaElement` behavior?

**Comment by owenniblock** [comment]
@seanpdoyle is it possible to get a bit more context on where and how this change would be used?

As @jscholes points out - `contenteditable` is not a feature we actively encourage using due to how difficult it is to make accessible for screen reader users. We've been encouraging developers to use text inputs marked as a `combobox` for a while now so having the full context of your intended use-case here would help us make decisions (and provide guidance).

I would not be surprised if `<text-expander>` comes with some accessibility issues (I'll check with the rest of the accessibility team but I don't believe we've assessed this component yet). We're encouraging people to use the AutoComplete element where possible and currently working on guidance for an accessible query builder pattern.

**Comment by seanpdoyle** [comment]
> is it possible to get a bit more context on where and how this change would be used

I'm hoping to implement `@`-mentions powered by Trix. Something like:

```html
<text-expander keys="@">
  <trix-editor name="article[body]" input="article_body_input" ...></trix-editor>
  <input type="hidden" id="article_body_input">
</text-expander>
```

The `<text-expander>` element (and its `Combobox` instance behind the scenes) would be involved in listening for `input` events, scanning for `@` characters, driving a `<turbo-frame>` (or `fetch` request), and presenting the options. Trix has built-in support for attachments and selection-replacement, so the rest of the experience wouldn't require any changes to the packages.

To be honest, when I started to poke around in the `<text-expander>` repository, I did not expect `combobox-nav` to be a transitive dependency in need of changes. If there are other packages that are a better fit than `<text-expander>`, or if there is a way to change `<text-expander>` to serve `[contenteditable][role="textbox"]` elements, I'm in favor of exploring that path.

**Comment by jscholes** [comment]
@seanpdoyle Is this change driven by a need within a GitHub product, or something you're working on outside of GitHub?  If the former, you'll need to connect internally with the GitHub Accessibility team, as there are wider concerns posed by the use of a third party editor within the GitHub ecosystem.  If the latter, it may be more appropriate to fork this component to meet your needs, as I suspect this use case isn't one we want to encourage right now.  But I defer to others on that decision.

**Comment by owenniblock** [comment]
>  it may be more appropriate to fork this component to meet your needs

Yes, I agree with @jscholes here. We're not going to look at allowing `contenteditable` on this component right now because it doesn't match our direction or use of this component internally. Sorry to be the bearer of bad news!

**Review by inkblotty — CHANGES_REQUESTED** [review]
Hi @seanpdoyle 👋 

Because this is a GitHub-supported web component, we want to avoid supporting potentially inaccessible patterns. Using `contenteditable` or a `textbox` role within a combobox pattern isn't accessible, and we want to avoid creating a confusing and exclusionary experience for users with disabilities.

We don't have specific guidance published publicly yet on `contenteditable`, but you can read more about the [Accessibility guidelines](https://primer.style/design/accessibility) we've released within our design system, Primer, if you're interested.

I understand your use case of wanting to swap out the source for the options based on user input, and that's something we're looking to add into Primer soon. In the meantime, feel free to fork this repository if you need `contenteditable` support.

**Comment by owenniblock** [comment]
Closing this PR, sorry we can't support this request @seanpdoyle.

**Comment by seanpdoyle** [comment]
Thank you for the consideration and ensuing discussion!

> In the meantime, feel free to fork this repository if you need contenteditable support, as @jscholes and @owenniblock suggest.

I've forked `github/text-expander-element` and made the necessary modifications to support Trix: https://github.com/thoughtbot/trix-mentions-element.

It still depends on this repository (`github/combobox-nav`) in its current upstream form, by passing an instance of `<trix-editor>` (an element that relies on `[contenteditable]`) cast to an `HTMLTextAreaElement` in the TypeScript. I haven't hit any roadblocks yet, but will fork if necessary.

Thanks again!

**Pull request closed without merging**
